package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderDeliveryRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Request Author")
	private java.lang.String requestAuthor;
	@org.kie.api.definition.type.Label("Delivery id")
	private java.lang.String deliveryId;
	@org.kie.api.definition.type.Label("Note about delivery")
	private java.lang.String note;
	@org.kie.api.definition.type.Label("Priority")
	private int priority;
	@org.kie.api.definition.type.Label(value = "Contact email")
	private java.lang.String email;

	public OrderDeliveryRequest() {
	}

	public java.lang.String getRequestAuthor() {
		return this.requestAuthor;
	}

	public void setRequestAuthor(java.lang.String requestAuthor) {
		this.requestAuthor = requestAuthor;
	}

	public java.lang.String getDeliveryId() {
		return this.deliveryId;
	}

	public void setDeliveryId(java.lang.String deliveryId) {
		this.deliveryId = deliveryId;
	}

	public java.lang.String getNote() {
		return this.note;
	}

	public void setNote(java.lang.String note) {
		this.note = note;
	}

	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public OrderDeliveryRequest(java.lang.String requestAuthor,
			java.lang.String deliveryId, java.lang.String note, int priority,
			java.lang.String email) {
		this.requestAuthor = requestAuthor;
		this.deliveryId = deliveryId;
		this.note = note;
		this.priority = priority;
		this.email = email;
	}

}