package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class OrderCancellationDecision implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String email;
	private boolean cancellable;

	private java.lang.String message;

	public OrderCancellationDecision() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public boolean isCancellable() {
		return this.cancellable;
	}

	public void setCancellable(boolean cancellable) {
		this.cancellable = cancellable;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public OrderCancellationDecision(java.lang.String id,
			java.lang.String email, boolean cancellable,
			java.lang.String message) {
		this.id = id;
		this.email = email;
		this.cancellable = cancellable;
		this.message = message;
	}

}