package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrescriptionBasedDrugOrderRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String drug;
	private int amount;

	@org.kie.api.definition.type.Label("Personal Identification Number")
	private java.lang.String personalIdentificationNumber;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Contact email")
	private java.lang.String email;

	public PrescriptionBasedDrugOrderRequest() {
	}

	public java.lang.String getDrug() {
		return this.drug;
	}

	public void setDrug(java.lang.String drug) {
		this.drug = drug;
	}

	public java.lang.String getPersonalIdentificationNumber() {
		return this.personalIdentificationNumber;
	}

	public void setPersonalIdentificationNumber(
			java.lang.String personalIdentificationNumber) {
		this.personalIdentificationNumber = personalIdentificationNumber;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public PrescriptionBasedDrugOrderRequest(java.lang.String drug, int amount,
			java.lang.String personalIdentificationNumber,
			java.lang.String name, java.lang.String email) {
		this.drug = drug;
		this.amount = amount;
		this.personalIdentificationNumber = personalIdentificationNumber;
		this.name = name;
		this.email = email;
	}

}