package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class prescriptionValidity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean valid;

	public prescriptionValidity() {
	}

	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	public prescriptionValidity(boolean valid) {
		this.valid = valid;
	}

}