package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrescriptionBasedDrugOrderResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Contact email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Valid order")
	private boolean valid;
	@org.kie.api.definition.type.Label("Available")
	private boolean available;

	@org.kie.api.definition.type.Label("Personal Identification Number")
	private java.lang.String personalIdentificationNumber;

	@org.kie.api.definition.type.Label(value = "Prescription")
	private java.lang.String prescription;

	public PrescriptionBasedDrugOrderResult() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public java.lang.String getPersonalIdentificationNumber() {
		return this.personalIdentificationNumber;
	}

	public void setPersonalIdentificationNumber(
			java.lang.String personalIdentificationNumber) {
		this.personalIdentificationNumber = personalIdentificationNumber;
	}

	public java.lang.String getPrescription() {
		return this.prescription;
	}

	public void setPrescription(java.lang.String prescription) {
		this.prescription = prescription;
	}

	public PrescriptionBasedDrugOrderResult(java.lang.String name,
			java.lang.String email, boolean valid, boolean available,
			java.lang.String personalIdentificationNumber,
			java.lang.String prescription) {
		this.name = name;
		this.email = email;
		this.valid = valid;
		this.available = available;
		this.personalIdentificationNumber = personalIdentificationNumber;
		this.prescription = prescription;
	}

}