package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrescriptionBasedDrugOrderRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Personal Identification Number")
	private java.lang.String personalIdentificationNumber;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Contact email")
	private java.lang.String email;

	private java.lang.String prescription;

	public PrescriptionBasedDrugOrderRequest() {
	}

	public java.lang.String getPersonalIdentificationNumber() {
		return this.personalIdentificationNumber;
	}

	public void setPersonalIdentificationNumber(
			java.lang.String personalIdentificationNumber) {
		this.personalIdentificationNumber = personalIdentificationNumber;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPrescription() {
		return this.prescription;
	}

	public void setPrescription(java.lang.String prescription) {
		this.prescription = prescription;
	}

	public PrescriptionBasedDrugOrderRequest(
			java.lang.String personalIdentificationNumber,
			java.lang.String name, java.lang.String email,
			java.lang.String prescription) {
		this.personalIdentificationNumber = personalIdentificationNumber;
		this.name = name;
		this.email = email;
		this.prescription = prescription;
	}

}