package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessedRegistrationInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "Number")
	private java.lang.String number;
	@org.kie.api.definition.type.Label(value = "Age")
	private java.lang.String age;
	@org.kie.api.definition.type.Label(value = "Note about User")
	private java.lang.String note;

	public ProcessedRegistrationInformation() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public java.lang.String getAge() {
		return this.age;
	}

	public void setAge(java.lang.String age) {
		this.age = age;
	}

	public java.lang.String getNote() {
		return this.note;
	}

	public void setNote(java.lang.String note) {
		this.note = note;
	}

	public ProcessedRegistrationInformation(java.lang.String name,
			java.lang.String email, java.lang.String number,
			java.lang.String age, java.lang.String note) {
		this.name = name;
		this.email = email;
		this.number = number;
		this.age = age;
		this.note = note;
	}

}