package com.myspace.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RegistrationResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean alreadyRegistered;
	private java.lang.String errorMessage;

	public RegistrationResponse() {
	}

	public java.lang.Boolean getAlreadyRegistered() {
		return this.alreadyRegistered;
	}

	public void setAlreadyRegistered(java.lang.Boolean alreadyRegistered) {
		this.alreadyRegistered = alreadyRegistered;
	}

	public java.lang.String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public RegistrationResponse(java.lang.Boolean alreadyRegistered,
			java.lang.String errorMessage) {
		this.alreadyRegistered = alreadyRegistered;
		this.errorMessage = errorMessage;
	}

}